// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful'
import { Document } from '@contentful/rich-text-types'

export interface IBitBearFields {
  /** Name */
  name?: string | undefined

  /** Nickname */
  nickname: string

  /** slug */
  slug?: string | undefined

  /** locale */
  locale?: string | undefined

  /** shareText */
  shareText: string

  /** description */
  description: Document

  /** ogpImage */
  ogpImage?: Asset | undefined

  /** keyVisualImage */
  keyVisualImage: Asset

  /** metadata */
  metadata?: Record<string, any> | undefined
}

export interface IBitBear extends Entry<IBitBearFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'bitBear'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export type CONTENT_TYPE = 'bitBear'

export type LOCALE_CODE = 'ja'

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'ja'
